version: "3.9"

services:
  db:
    image: postgres:16
    container_name: projectBack
    restart: unless-stopped
    environment:
      POSTGRES_DB: clean_nest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d clean_nest"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redisQueue
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: .
    container_name: appBack
    environment:
      DATABASE_URL: "postgresql://user:pass@db:5432/clean_nest"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      QUEUE_SUBMISSIONS: "submissions"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  worker_submissions:
    build: .
    container_name: workerSubmissions
    command: npm run start:worker
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      QUEUE_SUBMISSIONS: "submissions"
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

volumes:
  db_data: